version: "3.8"
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:10.16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=strapi
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
